validation_level: medium
description: "Balanced security - suitable for trusted development environments"
allowed_commands:
  # File operations (expanded)
  ls:
    allowed_args: ['-l', '-a', '-la', '-h', '-R', '-1', '-F', '-t', '-S', '--help']
    description: 'List directory contents'
  cat:
    allowed_args: ['-n', '-b', '-s', '--help']
    description: 'Display file contents'
    requires_file: true
  head:
    allowed_args: ['-n', '-c', '--help']
    description: 'Display first lines of file'
    requires_file: true
  tail:
    allowed_args: ['-n', '-c', '-f', '--help']
    description: 'Display last lines of file'
    requires_file: true
  file:
    allowed_args: ['--help']
    description: 'Determine file type'
    requires_file: true
  wc:
    allowed_args: ['-l', '-w', '-c', '--help']
    description: 'Word, line, character count'
    requires_file: true
  pwd:
    allowed_args: ['--help']
    description: 'Print working directory'
  find:
    allowed_args: ['-name', '-type', '-maxdepth', '--help']
    description: 'Find files and directories'
  tree:
    allowed_args: ['-L', '-a', '--help']
    description: 'Display directory tree'
  whoami:
    allowed_args: ['--help']
    description: 'Show current user'
  id:
    allowed_args: ['--help']
    description: 'Show user and group IDs'
  uname:
    allowed_args: ['-a', '-r', '-s', '--help']
    description: 'System information'
  date:
    allowed_args: ['--help']
    description: 'Show current date and time'
  uptime:
    allowed_args: ['--help']
    description: 'Show system uptime'
  df:
    allowed_args: ['-h', '--help']
    description: 'Show disk space usage'
  free:
    allowed_args: ['-h', '--help']
    description: 'Show memory usage'
  ps:
    allowed_args: ['aux', 'ef', '-u', '-p', '--help']
    description: 'Process status'
  netstat:
    allowed_args: ['-tuln', '-r', '--help']
    description: 'Network statistics'
  lsof:
    allowed_args: ['-i', '-p', '-u', '--help']
    description: 'List open files'
  # Text processing (expanded)
  grep:
    allowed_args: ['-n', '-i', '-r', '-v', '-c', '-l', '-w', '-x', '-E', '-F', '--help']
    description: 'Search text patterns'
    requires_file: true
  sed:
    allowed_args: ['-n', '-e', '-f', '--help']
    description: 'Stream editor'
    requires_file: true
  awk:
    allowed_args: ['-F', '-v', '--help']
    description: 'Pattern scanning and processing'
    requires_file: true
  sort:
    allowed_args: ['-n', '-r', '--help']
    description: 'Sort lines'
    requires_file: true
  uniq:
    allowed_args: ['-c', '--help']
    description: 'Report unique lines'
    requires_file: true
  # Development tools (expanded)
  node:
    allowed_args: ['--version', '--help', '-e', '-p', '--eval', '--print']
    description: 'Node.js runtime'
  npm:
    allowed_args: ['--version', 'list', 'ls', 'info', 'view', 'search', 'outdated', '--help']
    description: 'NPM operations'
  git:
    allowed_args: ['status', 'log', '--oneline', 'branch', 'diff', 'show', 'config', '--help']
    description: 'Git operations'
  which:
    allowed_args: ['--help']
    description: 'Locate command'
  type:
    allowed_args: ['--help']
    description: 'Display command type'
  man:
    allowed_args: ['--help']
    description: 'Manual pages'
    requires_file: true
  help:
    allowed_args: []
    description: 'Help command'
  echo:
    allowed_args: ['--help']
    description: 'Display text (limited)'

forbidden_patterns:
  - '[;&|`$(){}]'  # Command injection
  - '\brm\b -rf|\brm\b -fr'  # Dangerous rm operations
  - '\bsudo\b|\bsu\b'  # Privilege escalation
  - '\bkill\b -9|\bkillall\b'  # Dangerous process termination
  - '\bchmod\b 777|\bchown\b root'  # Dangerous permission changes

file_path_restrictions:
  enabled: true
  pattern: '^/?[a-zA-Z0-9._/-]+$'
  max_path_length: 1000

environment_policy:
  mode: blacklist
  blocked_vars: ['PASSWORD', 'SECRET', 'TOKEN', 'KEY', 'PRIVATE']

limits:
  max_arguments: 20
  max_command_length: 2000
  timeout_max: 30000
  timeout_default: 10000
